### ISSUE TITLE
Repeating REST errors in favorites for PDS member copy and rename

### ISSUE THREAD

**Issue by phaumer** [zowe/zowe-explorer-vscode#3548]
Moved from https://github.com/IBM/zopeneditor-about/issues/493 
Submitted by @johntgatesjr

**Describe the bug**

## Development environment used

- Zowe Explorer Version: 3.1.1

- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3):  MacOS 15.3.2

- Logs attached: yes 

## Problem Description
After pds member copy and rename, below error is observed.

Detailed steps for reproducing the problem:

1. First step
Copy PDS member.  Paste into same PDS.  Rename.  Action is successful but generates below error in log and popup window.

### Observed behavior

-Zowe Explorer 3.1.1
This log file can be found at /Users/john.gates/.vscode/extensions/zowe.vscode-extension-for-zowe-3.1.1
Zowe Explorer log level: INFO
[2025/03/26 08:16:09] [INFO] Zowe home directory is located at /Users/john.gates/.zowe
[2025/03/26 08:16:09] [INFO] No custom credential managers found, using the default instead.
[2025/03/26 08:16:09] [INFO] Zowe Explorer is using the team configuration file "zowe.config.json"
[2025/03/26 08:16:09] [INFO] Zowe profiles initialized successfully.
[2025/03/26 08:16:09] [WARN] Skipping creation of favorited profile. Error: Zowe Explorer Profiles Cache error: Could not find profile named: zos23-6.
[2025/03/26 08:16:09] [INFO] No custom credential managers found, using the default instead.
[2025/03/26 08:16:11] [INFO] Zowe Explorer has activated successfully.
[2025/03/26 10:11:21] [ERROR] Error: Rest API failure with HTTP(S) status 404
ISRZ002 Data set not cataloged - 'ZOSMF_ZOS23-6' was not found in catalog.
LMINIT error
{
  errorDetails: [s [Error]: Rest API failure with HTTP(S) status 404
  ISRZ002 Data set not cataloged - 'ZOSMF_ZOS23-6' was not found in catalog.
  LMINIT error
  	at m.populateError (/Users/john.gates/.vscode/extensions/zowe.vscode-extension-for-zowe-3.1.1/out/src/vendors.extension.js:416:284)
  	at x (/Users/john.gates/.vscode/extensions/zowe.vscode-extension-for-zowe-3.1.1/out/src/vendors.extension.js:403:6976)
  	at m.onEnd (/Users/john.gates/.vscode/extensions/zowe.vscode-extension-for-zowe-3.1.1/out/src/vendors.extension.js:403:7217)
  	at IncomingMessage.<anonymous> (/Users/john.gates/.vscode/extensions/zowe.vscode-extension-for-zowe-3.1.1/out/src/vendors.extension.js:403:5394)
  	at IncomingMessage.emit (node:events:530:35)
  	at endReadableNT (node:internal/streams/readable:1698:12)
  	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)] {
    mDetails: {
      msg: 'Rest API failure with HTTP(S) status 404\n' +
        "ISRZ002 Data set not cataloged - 'ZOSMF_ZOS23-6' was not found in catalog.\n" +
        'LMINIT error',
      causeErrors: `{"category":4,"rc":8,"reason":0,"message":"LMINIT error","details":["ISRZ002 Data set not cataloged - 'ZOSMF_ZOS23-6' was not found in catalog."]}`,
      source: 'http',
      errorCode: 404,
      protocol: 'https',
      port: 10443,
      host: 'zos23-6.protegrity.com',
      basePath: '',
      httpStatus: 404,
      errno: undefined,
      syscall: undefined,
      payload: undefined,
      headers: [
        { 'Accept-Encoding': 'gzip' },
        { 'X-IBM-Attributes': 'base' },
        { 'X-IBM-Max-Items': '0' },
        { 'X-IBM-Response-Timeout': '30' },
        { 'X-CSRF-ZOSMF-HEADER': true }
      ],
      resource: '/zosmf/restfiles/ds/zosmf_zos23-6/member',
      request: 'GET',
      additionalDetails: 'Received HTTP(S) error 404 = Not Found.\n' +
        '\n' +
        'Protocol:          https\n' +
        'Host:              zos23-6.protegrity.com\n' +
        'Port:              10443\n' +
        'Base Path:         \n' +
        'Resource:          /zosmf/restfiles/ds/zosmf_zos23-6/member\n' +
        'Request:           GET\n' +
        'Headers:           [{"Accept-Encoding":"gzip"},{"X-IBM-Attributes":"base"},{"X-IBM-Max-Items":"0"},{"X-IBM-Response-Timeout":"30"},{"X-CSRF-ZOSMF-HEADER":true}]\n' +
        'Payload:           undefined\n' +
        'Auth type:         basic\n' +
        'Allow Unauth Cert: true'
    },
    mMessage: 'Rest API failure with HTTP(S) status 404\n' +
      "ISRZ002 Data set not cataloged - 'ZOSMF_ZOS23-6' was not found in catalog.\n" +
      'LMINIT error'
  },
  apiType: 'mvs',
  profile: undefined,
  scenario: 'Retrieving response from MVS list API'
}
### Expected behavior

-

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version:
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by traeok** [comment]
I cannot reproduce this with Zowe Explorer v3.1.2. This may have been resolved as part of a more recent PR for copy/paste data set fixes.

**Comment by johntgatesjr** [comment]
I just tried 3.1.2 and my problem is not fixed.  And now 3.1.2 introduces a new problem.  All of my datasets in my Favorites list are now doubled.  That is - I have two copies of every dataset in my list.

**Comment by traeok** [comment]
@johntgatesjr Are you copy/pasting from the Favorites section? I should clarify that I'm performing this action from a z/OSMF profile that is not favorited. That scenario doesn't seem to reproduce the error on my machine, but I can test the copy/paste in other scenarios.

**Comment by johntgatesjr** [comment]
Forgot to mention that.  Yes.  We are working in a Favorites list.
